//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOTEL.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOTEL()
        {
            this.TBLHAREKET = new HashSet<TBLHAREKET>();
        }
    
        public int ID { get; set; }
        public string NO { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public Nullable<int> SUBE { get; set; }
        public string KAT { get; set; }
        public string YATAK { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string RESIM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHAREKET> TBLHAREKET { get; set; }
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        public virtual TBLSUBE TBLSUBE { get; set; }
    }
}
